### ISSUE TITLE
'filter[serverType]' and 'filter[rankingType]' are no longer working

### ISSUE THREAD

**Issue by xKynn** [gamelocker/battlerite-assets#3]
Now returns as a 400 and bad param

**Comment by ankemp** [comment]
@bguilder said in discord: 
> Hey @API, just a heads up that the new match.tags field released on Thursday had a bug that was causing delays in search times. We have rolled back that feature and will be working on a fix next week. Thank you for your patience and I hope you all have an awesome weekend!

**Comment by jsmienk** [comment]
@ankemp Is that Discord for Gamelocker developers or also for people interested/working with the API like me?

**Comment by Harmon758** [comment]
The Discord server that quote is from is the official Battlerite Discord server:
https://discord.gg/br
